## Python List

In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Fixed type arrays in Python

In [8]:
import array

In [11]:
A = array.array('i', L)
# 'i' is a type code indicating the contents are integers
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [12]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [13]:
# NumPy arrays contain the same type
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [14]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
a = np.array([1,2,3,4])

In [18]:
type(a[0])

numpy.int64

In [20]:
# Multidimentional
np.array([range(i, i + 3) for i in [2, 4, 6]])
# [2, 4, 6] -> Rows and each rows begins with the element and ranges(i, i+3) for columns

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch
- np.zeros()
- np.ones()
- np.full()
- np.arange()
- np.linspace()
- np.random.random()
- np.random.normal()
- np.eye()
- np.empty()

In [21]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
# Create a 3x3 array of uniformly distributed 
# random values between 1 and 1
np.random.random((3, 3))

array([[0.89277033, 0.79589153, 0.62693335],
       [0.44741512, 0.52732182, 0.31971555],
       [0.13165622, 0.70684847, 0.2251368 ]])

In [28]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 0.52602596,  0.44784189,  0.70806923],
       [ 0.08631329, -0.13380195,  0.20931181],
       [-0.4942889 ,  0.67318805,  0.21226675]])

In [29]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])