## Structured Data: NumPy's Structured Arrays

In [1]:
import numpy as np

In [2]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [3]:
x = np.zeros(4, dtype=int)

In [4]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                         'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [5]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [6]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [9]:
# Get the name from the last row
data[-1]['name']

'Doug'

In [11]:
# Get names where age is under 30
data[data['age']< 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

### Creating Structured Arrays

In [12]:
np.dtype({'names':('name', 'age', 'weight'),
         'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [13]:
# numerical types can be specified with Python types or NumPy dtypes
np.dtype({'names':('name', 'age', 'weight'),
         'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [14]:
# compount type can also be specified as list of tuples
np.dtype([('name', 'S10'),('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [15]:
# If the names of the types do not matter to you
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

The shortened string format codes may seem confusin, but they are built on simple principles. The first (optional)
character is < or >, which means "little endian" or "big endian," respectively, and specifies the ordering convention for significant bits. The next character specifies the type of data: charactrs, bytes, ints, floating points, and so on.

| Character | Description | Example |
| ----- | ----- | -----|
| 'b' | Byte | np.dtype('b') |
| 'i' | Signed Integer | np.dtype('i4') == np.int32 |
| 'u' | Unsigned integer | np.dtype('u1') == np.uint8 |
| 'f' | Floating point | np.dtype('f8') == np.int64 |
| 'c' | Complex floating point | np.dtype('c16') == np.complex128 |
| 'S', 'a' | string | np.dtype('S5') |
| 'U' | Unicode string | np.dtype('U') == np.str_ |
| 'V' | Raw data (void) | np.dtype('V') == np.void |

### More Advanced Compound Types

In [16]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### RecordArrays: Structured Arrays with a Twist
NumPy also provides the np.recarray class, which is almost identical to the structured arrays just described, but with one additional feature: fields can be accessed as attributes rather than a dictionary keys.

In [17]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [18]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax.

In [20]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

134 ns ± 1.12 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.21 µs ± 9.44 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.81 µs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
