In [1]:
from sklearn import preprocessing
import numpy as np

In [5]:
X = np.array([[1., -2., 2.],
             [3., 0., 0.],
             [0., 1., -1.]])

## Standardizing features

Process of scaling the data to have zero mean and unit variance. (x-miu)/sigma

In [6]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[-0.26726124, -1.33630621,  1.33630621],
       [ 1.33630621,  0.26726124, -0.26726124],
       [-1.06904497,  1.06904497, -1.06904497]])

In [7]:
X_scaled.mean(axis=0)

array([7.40148683e-17, 0.00000000e+00, 0.00000000e+00])

In [8]:
X_scaled.mean(axis=1)

array([-0.08908708,  0.4454354 , -0.35634832])

In [9]:
X_scaled.std(axis=0)

array([1., 1., 1.])

## Normalizing features

- L1 Norm: Manhattan distance
- L2 Norm: Euclidean distance

In [10]:
X_normalized_l1 = preprocessing.normalize(X, norm='l1')
X_normalized_l1

array([[ 0.2, -0.4,  0.4],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.5, -0.5]])

In [12]:
X_normalized_l2 = preprocessing.normalize(X, norm='l2')
X_normalized_l2

array([[ 0.33333333, -0.66666667,  0.66666667],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

## Scaling features to a range

Get features to lie between a given minimum and maximum value

In [13]:
min_max_scaler = preprocessing.MinMaxScaler()
X_min_max = min_max_scaler.fit_transform(X)
X_min_max

array([[0.33333333, 0.        , 1.        ],
       [1.        , 0.66666667, 0.33333333],
       [0.        , 1.        , 0.        ]])

In [15]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(-10, 10))
X_min_max2 = min_max_scaler.fit_transform(X)
X_min_max2

array([[ -3.33333333, -10.        ,  10.        ],
       [ 10.        ,   3.33333333,  -3.33333333],
       [-10.        ,  10.        , -10.        ]])

## Binarizing features

In [16]:
X

array([[ 1., -2.,  2.],
       [ 3.,  0.,  0.],
       [ 0.,  1., -1.]])

In [17]:
binarizer = preprocessing.Binarizer(threshold=0.5)
X_binarized = binarizer.transform(X)
X_binarized

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

## Handling the missing data

Imputation of missing values, options:

- 'mean': replaces all the nan values with mean value alog a specified axis of the matrix (default: axis=0)
- 'median': replaces all the nan values with median value along a specified axis of th matrix (defaul: axis=0)
- 'most_frequent': replaces all the nan values with the most frequent value along a specified axis of the matrix (default: axis=0)

In [18]:
from numpy import nan
X = np.array([[nan, 0, 3],
             [2, 9, -8],
             [1, nan, 1],
             [5, 2, 4],
             [7, 6, -3]])

In [19]:
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean')
X2 = imp.fit_transform(X)
X2

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 3.75,  0.  ,  3.  ],
       [ 2.  ,  9.  , -8.  ],
       [ 1.  ,  4.25,  1.  ],
       [ 5.  ,  2.  ,  4.  ],
       [ 7.  ,  6.  , -3.  ]])

In [20]:
np.mean(X[1:, 0]), X2[0, 0]

(3.75, 3.75)

In [26]:
# from sklearn.impute import SimpleImputer
imp = Imputer(strategy='median')
X3 = imp.fit_transform(X)
X3

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 3.5,  0. ,  3. ],
       [ 2. ,  9. , -8. ],
       [ 1. ,  4. ,  1. ],
       [ 5. ,  2. ,  4. ],
       [ 7. ,  6. , -3. ]])

In [27]:
np.median(X[1:, 0]), X3[0, 0]

(3.5, 3.5)